### ISSUE TITLE
wizcon connection issue

### ISSUE THREAD

**Issue by djacobson** [rgomezjnr/wizctrl#5]
I'm wondering if a recent Python or other library update has caused this? The following basic wizcon command was working fine just a day or two ago. FYI: my bulb is ping'able...

pi@jpimain:~ $ wizcon 192.168.50.122 OFF
Task exception was never retrieved
future: <Task finished coro=<DatagramClient.send() done, defined at /usr/local/lib/python3.7/dist-packages/asyncio_dgram/aio.py:148> exception=ConnectionRefusedError(111, 'Connection refused')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/asyncio_dgram/aio.py", line 152, in send
    await super()._send(data)
  File "/usr/local/lib/python3.7/dist-packages/asyncio_dgram/aio.py", line 106, in _send
    _ = self.exception
  File "/usr/local/lib/python3.7/dist-packages/asyncio_dgram/aio.py", line 59, in exception
    raise exc
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 954, in _read_ready
    data, addr = self._sock.recvfrom(self.max_size)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by djacobson** [comment]
I have yet to pull but, I was wondering if line 127 in wizcon.py might need to be changed to something like:

asyncio.run_until_complete(asyncio.gather(exc()))

...per:

https://stackoverflow.com/questions/30361824/asynchronous-exception-handling-in-python/30364143#30364143

?

I'm wondering if Philips locked down the port in a firmware update? ...but, I don't see any issues in the wizlight repo. ?

**Comment by djacobson** [comment]
Never mind. After doing a `wizlight discover` , I saw that my wiz bulb had changed IPs. Odd error though.

**Comment by rgomezjnr** [comment]
I have seen a number of new updates from pywizlight but haven't reviewed or tested the new versions yet. The error handling in wizcon could be better such as when an incorrect IP address is entered. I'll have to take a look at both of these points soon.

**Comment by rgomezjnr** [comment]
As a workaround solution you could also look into setting a static IP address for your bulb in your router settings. I've done this myself and found it to be useful since the bulb would be reassigned a new IP address when I flipped the physical light switch instead of using wizcon or the Wiz app.
