### ISSUE TITLE
Brightness command not working with Philips Astra smart batten.

### ISSUE THREAD

**Issue by rp1231** [rgomezjnr/wizctrl#7]
Hi,

The Brightness command is not working with Philips Astra smart batten.
Maybe it is because it does not have rgb but only white and yellow modes?

The scenes that are present on the mobile app seem to be working fine.

Firmware version: 1.26.0
Model ID: 23096

Thanks

**Comment by djacobson** [comment]
What version of pywizlight do you have installed? Mine below:

$ pip3 show pywizlight
Name: pywizlight
Version: 0.4.16
Summary: A python connector for WiZ light bulbs (e.g SLV Play)
Home-page: https://github.com/sbidy/pywizlight
Author: Stephan Traub
Author-email: sbidy@hotmail.com
License: MIT
Location: /home/pi/src/pywizlight
Requires: asyncio-dgram, click
Required-by: wizcon

**Comment by rgomezjnr** [comment]
Hi rp1231

Are you able to adjust the brightness using the Wiz app? eg using the brightness slider control

Can you provide the exact wizcon commands you are attempting to run?

Does the following command set the brightness to the minimum brightness level?

`wizcon --brightness 1 IP ON`

Does the following command set the brightness to the maximum brightness level?

`wizcon --brightness 255 IP ON`

**Comment by rp1231** [comment]
@djacobson Here is my pywizlight version:
```
Name: pywizlight
Version: 0.5.13
Summary: A python connector for WiZ light bulbs (e.g SLV Play)
Home-page: https://github.com/sbidy/pywizlight
Author: Stephan Traub
Author-email: sbidy@hotmail.com
License: MIT
Location: c:\python310\lib\site-packages
Requires: click
Required-by: wizcon
```

@rgomezjnr Everything works fine with the wiz app, brightness control, colour temperature etc.

**Comment by rp1231** [comment]
Strange but the command seems to be working today when I tried it.....
Closing this for now, but will open it again if I come across the same situation again.......

Thanks,
And sorry for the trouble.
