### ISSUE TITLE
[Feature request] 'get' command to for power state(on/off), brightness, color temperature etc.

### ISSUE THREAD

**Issue by rp1231** [rgomezjnr/wizctrl#8]
Hi,

It would be nice to have a 'get' command to get the power state(on/off), brightness, color temperature etc.

Thanks

**Comment by rgomezjnr** [comment]
Hi does [wizlight](https://github.com/sbidy/pywizlight#cli) work for you?

```
$ wizlight state
IP address of the bulb: IP
Get the state from IP
{'mac': MAC, 'rssi': -56, 'src': '', 'state': True, 'sceneId': 23, 'speed': 100, 'dimming': 100}
```

**Comment by rp1231** [comment]
Yes it works, 
But the problem is that it requires an extra  step of inputting the ip address.
The ip address can't be passed as an argument like it can be in wizcon.

I'm trying to use this for a rainmeter skin, so that it can show a deactivated state when the bulb is off.

**Comment by rgomezjnr** [comment]
It works for me in version 0.5.14. if I add the `--ip` option:

```
wizlight state --ip IP
Get the state from IP
{'mac': 'X', 'rssi': -63, 'src': '', 'state': False, 'sceneId': 11, 'temp': 2700, 'dimming': 100}
```

```
wizlight state --help
Usage: wizlight state [OPTIONS]

  Get the current state of a given bulb.

Options:
  --ip TEXT  IP address of the bulb.
  --help     Show this message and exit.
```

**Comment by rp1231** [comment]
Aah I see, 
That works for me.
Thanks.

**Comment by rp1231** [comment]
Is it possible to get only the state (true or false) via a command?
Thanks

**Comment by rgomezjnr** [comment]
Here's a roundabout quick and dirty way of doing it I think, assuming you're using bash shell:

wizlight state --ip 192.168.1.100 > bulb-state.json
sed 's/'\''/\"/g' < bulb-state.json
python -c 'import json; print(json.load(open("bulb-state.json"))["state"])'
