### ISSUE TITLE
Light turns right back on after turning it off using the cli

### ISSUE THREAD

**Issue by rp1231** [rgomezjnr/wizctrl#9]
A lot of the times when I'm using the cli to turn a light off, it will turn right back on.
This doesn't happen always but it happens often enough for it to be annoying.
Would you have any idea as to why this would be happening?
Thanks

**Comment by rgomezjnr** [comment]
What version of wizcon are you using? Run `wizcon --version`

What version of pywizlight do you have installed? Run `pip3 list`

What smart bulb do you have?

I haven't run into that issue. I have the following:

wizcon 0.3.0
pywizlight 0.5.14

**Comment by rgomezjnr** [comment]
Do you see the same behavior if you try to run the `wizlight on` command?

```
wizlight on
IP address of the bulb: 192.168.1.103
Kelvin for temperature. [3000]: 3000
Set the brightness value 0-255 [128]: 128
Turning on 192.168.1.103
```

**Comment by rp1231** [comment]
> What version of wizcon are you using? Run `wizcon --version`
> 
> What version of pywizlight do you have installed? Run `pip3 list`
> 
> What smart bulb do you have?
> 
> I haven't run into that issue. I have the following:
> 
> wizcon 0.3.0 pywizlight 0.5.14

I have the same versions as yours

And yes when I encounter the problem, I encounter it with the wizlight off command, not the on command.
Same with wizcon, the problem used to happen only for the off command, not the on command.
I haven't encountered it today but the day I posted this I was encountering it the whole day.

**Comment by rp1231** [comment]
Actually encountered the problem again just right now.
It happens even when I use the toggle command, But only when I toggle it off.
I have a macro setup to execute the toggle command on keypress, If I toggle it off, It just turns back on again.
This happens intermittently, sometimes it works fine

**Comment by rp1231** [comment]
> 
> What smart bulb do you have?
> 
I have the philips astra line led batten

**Comment by rgomezjnr** [comment]
> I have the philips astra line led batten

Is this the light you have? [Philips Smart Wi-Fi LED Batten 24-Watt WiZ Connected](https://www.amazon.in/Philips-Connected-Tuneable-Compatible-Assistant/dp/B08QH2FGF8) I've searched for other batten lights, not all of them seem to officially support Wiz Wi-Fi control. What is the model number you have?

Do you see the same issue when you use the Wiz app on your phone?

Does turning the light off and back on via electrical hardware switch help at all?

If you're experiencing the same issue with the `wizlight off` command then maybe that means this is an underlying issue, e.g. with the library that wizcon uses, [pywizlight](https://github.com/sbidy/pywizlight), or the bulb firmware.

Maybe there's other devices or software running on your network that could be conflicting with your light?

Maybe try opening an issue in [pywizlight](https://github.com/sbidy/pywizlight). I looked through all their open and closed issues but did not see any directly related.

The only other thing I would suggest is trying [pywizlight](https://github.com/sbidy/pywizlight)'s [reboot](https://github.com/sbidy/pywizlight/blob/a11d2c7744d7110eb42ce8af5eddb3f6f40bd228/pywizlight/bulb.py#L632C15-L632C21) and [reset](https://github.com/sbidy/pywizlight/blob/a11d2c7744d7110eb42ce8af5eddb3f6f40bd228/pywizlight/bulb.py#L636) commands to see if that helps.

**Comment by rp1231** [comment]
> Is this the light you have? [Philips Smart Wi-Fi LED Batten 24-Watt WiZ Connected](https://www.amazon.in/Philips-Connected-Tuneable-Compatible-Assistant/dp/B08QH2FGF8) I've searched for other batten lights, not all of them seem to officially support Wiz Wi-Fi control. What is the model number you have?
> 

Yes this is the light I have.
The model number is 23096

> Do you see the same issue when you use the Wiz app on your phone?
> 

Yes I have the same issue when using the Wiz app on my phone. So I guess It's a problem on philips end and not with wizcon or with pywizlight

> Does turning the light off and back on via electrical hardware switch help at all?
> 

I'll try this out.

Thanks for the help.
